### ISSUE TITLE
Rethink case sensitivity

### ISSUE THREAD

**Issue by cschorn** [mschop/pathogen#15] opened 2020-09-25 09:41 UTC
Case sensitivity is an attribute of the underlying file system, not of the path string.

The current implementation has case sensitivity as a parameter for the methods like `contains`:

```php
$path = Path::fromString('/home/user');
$path->contains('User', false); // true
$path->contains('User', true); // false
```
Case sensitivity should be moved into the path classes long term.

**Comment by mschop** [comment] 2020-09-25 14:27
The problem is, that the current class structure is not really good for this. The following classes are used to represent a path:

**Generic File System** -> may be case insensitive or case sensitive

- AbsolutePath
- RelativePath

**Windows File System** -> case insensitive, case preserving

- AbsoluteWindowsPath
- RelativeWindowsPath

**Unix File System** -> can be case sensitive (linux, bsd's) or case insensitive (macOS)

- RelativeUnixPath
- AbsoluteUnixPath


### Possible solution
I personally don't like the taken approach by the previous maintainers of the lib. It doesn't matter, what exact operating system a specific path is used / built from. Instead a general class with optional features should be created.

This general class could have the following constructor options:
- isCaseSensitive: bool
- pathSeparator: string
- hasDrive: bool

Additionally, we only need one factory.

@cschorn  What do you think about this?

**Comment by cschorn** [comment] 2020-09-25 14:46
I'm having issues with `hasDrive`, plus Win paths have different restrictions.

**Comment by mschop** [comment] 2020-09-25 14:50
Well, but I would prefer to not represent those differences (like maximum depth) as separate classes. There may be more options, that I am not aware of now. I would need to figure this out.

What issues do you have with `hasDrive`? I would guess, you are complaining about the name of the variable right? E.g. `isDriveAgnostic`or something like that. (but this is a detail, that need to be though through wile programming.

**Comment by mschop** [comment] 2022-02-28 11:02
I close this issue, because this will be done in #20

**Closed as completed by mschop** 2022-02-28 11:02 UTC
